#version: '3.1'
#
#services:
#
#  mongo:
#    image: mongo
#    container_name: mongo_server
#    restart: always
#    ports:
#      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#      ME_CONFIG_BASICAUTH: false

version: "3.9"


services:
#  app:
#    build:
#      context: .
#    env_file:
#      - .env
#    ports:
#      - "5011:${PORT}"
#    volumes:
#      - .backend:/app
#      - /app/node_modules
#    restart: on-failure
#    command: sh -c "npm run start:dev"

  app:
    build:
      context: .
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: on-failure
    command: sh -c "npm run start:dev"

  db:
    image: mongo
    env_file:
      - .env
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_db:/data/db
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client:/usr/share/nginx/html
    restart: on-failure